openapi: 3.0.0
info:
  title: Cab Booking API
  version: 1.0.0
  description: API documentation for the Cab Booking application

paths:
  /auth/users/register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User registered successfully
        '429':
          description: Too many auth requests

  /auth/users/login:
    post:
      summary: Login a user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: User logged in successfully
        '429':
          description: Too many auth requests

  /users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        '200':
          description: A list of users
        '401':
          description: Unauthorized
        '429':
          description: Request limit exceeded

  /users/{userId}:
    get:
      summary: Get user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
        '401':
          description: Unauthorized
        '429':
          description: Request limit exceeded

  /auth/captain/register:
    post:
      summary: Register a new captain
      tags:
        - Captains
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Captain registered successfully
        '401':
          description: Unauthorized
        '429':
          description: Too many auth requests