version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:18

jobs:
  deploy:
    executor: default
    environment:
      DATABASE_URL: "postgresql://postgres:anuragsingh@34.68.128.8:5432/postgres"
      PGUSER: "postgres"
      PGPASSWORD: "anuragsingh"
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Create .env File
          command: |
            echo "PORT=$PORT" >> .env
            echo "NODE_ENV=$NODE_ENV" >> .env
            echo "API_URL=$API_URL" >> .env
            echo "CORS_ORIGIN=$CORS_ORIGIN" >> .env
            echo "RATE_LIMIT_WINDOW=$RATE_LIMIT_WINDOW" >> .env
            echo "RATE_LIMIT_MAX=$RATE_LIMIT_MAX" >> .env
            echo "SWAGGER_ENABLED=$SWAGGER_ENABLED" >> .env
            echo "DATABASE_URL=$DATABASE_URL" >> .env
            echo "JWT_SECRET=$JWT_SECRET" >> .env
            echo "FIREBASE_ADMIN_CREDENTIALS=$FIREBASE_ADMIN_CREDENTIALS" >> .env

      - run:
          name: Authenticate with Google Cloud
          command: |
            echo "$GCP_SA_KEY" > /tmp/gcp-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
            gcloud auth configure-docker gcr.io

      - run:
          name: Install Cloud SQL Auth Proxy
          command: |
            wget https://storage.googleapis.com/cloudsql-proxy/v1.33.3/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
            chmod +x cloud_sql_proxy
            ./cloud_sql_proxy -instances=$CLOUD_SQL_INSTANCE=tcp:5432 &
            sleep 10

      - run:
          name: Test Database Connection
          command: |
            PGPASSWORD="$PGPASSWORD" psql -h 34.68.128.8 -U postgres -d postgres -p 5432 -c "SELECT 1;"

      - run:
          name: Run Prisma Migrations
          command: |
            npm install -g prisma
            npx prisma migrate deploy

      - run:
          name: Build and Push Docker Image
          command: |
            docker buildx build --platform=linux/amd64 \
              -t gcr.io/$GCP_PROJECT_ID/prisma-backend:$CIRCLE_SHA1 --push .

      - run:
          name: Deploy to Cloud Run
          command: |
            gcloud run deploy prisma-backend \
              --image gcr.io/$GCP_PROJECT_ID/prisma-backend:$CIRCLE_SHA1 \
              --platform managed \
              --region us-central1 \
              --allow-unauthenticated \
              --add-cloudsql-instances=$CLOUD_SQL_INSTANCE \
              --set-env-vars DATABASE_URL="postgresql://postgres:anuragsingh@/cloudsql/$CLOUD_SQL_INSTANCE/postgres"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
