apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-backend
  labels:
    app: prisma-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prisma-backend
  template:
    metadata:
      labels:
        app: prisma-backend
    spec:
      containers:
        - name: prisma-backend
          image: gcr.io/innate-rite-447114-h4/prisma-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: prisma-db-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
      imagePullSecrets:
        - name: regcred