apiVersion: v1
kind: Service
metadata:
  name: prisma-backend-service
spec:
  type: LoadBalancer
  selector:
    app: prisma-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
