name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
        
      - name: Install dependencies
        run: npm install
        
      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud auth configure-docker gcr.io
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
        
      - name: Start Cloud SQL Auth Proxy
        run: |
          wget https://storage.googleapis.com/cloudsql-proxy/v1.33.3/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
          chmod +x cloud_sql_proxy
          ./cloud_sql_proxy -dir=/cloudsql -instances=${{ secrets.CLOUD_SQL_INSTANCE }} &
        
      - name: Debug Cloud SQL Proxy
        run: sleep 5 && ps aux | grep cloud_sql_proxy
        
      - name: Run Prisma Migrations
        run: |
          npm install -g prisma
          npx prisma migrate deploy
        env:
          DATABASE_URL: "postgresql://${{ secrets.DATABASE_USER_GCP }}:${{ secrets.DATABASE_PASSWORD_GCP }}@127.0.0.1:5432/${{ secrets.DATABASE_NAME_GCP }}"
      
      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform=linux/amd64 \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/prisma-backend:$GITHUB_SHA --push .
        
      - name: Debug Cloud Build Logs
        run: gcloud builds list --limit=5
        
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy prisma-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/prisma-backend:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --add-cloudsql-instances=${{ secrets.CLOUD_SQL_INSTANCE }} \
            --set-env-vars DATABASE_URL="postgresql://${{ secrets.DATABASE_USER_GCP }}:${{ secrets.DATABASE_PASSWORD_GCP }}@/cloudsql/${{ secrets.CLOUD_SQL_INSTANCE }}/${{ secrets.DATABASE_NAME_GCP }}"