name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 6: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: innate-rite-447114-h4

      # Step 7: Run Prisma Migrations
      - name: Run Prisma migrations
        run: npm run prisma:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Step 8: Build and Push Docker Image to Google Container Registry
      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/innate-rite-447114-h4/prisma-backend

      # Step 9: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy prisma-backend \
            --image gcr.io/innate-rite-447114-h4/prisma-backend \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --add-cloudsql-instances innate-rite-447114-h4:us-central1:reparo \
            --set-env-vars DATABASE_URL=${{ secrets.DATABASE_URL }}
